{% set name = "livvkit" %}
{% set version = "3.3.1" %}
{% set sha256 = "2aa07b0f1a5efed89d76976303fd784f7068471311c7ba49f49fe1a628e57f35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - livv = livvkit.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools_scm >=6.2
    - python-build
  run:
    - python >={{ python_min }}
    - jinja2
    - json_tricks >=3.11.0
    - loguru
    - matplotlib-base
    - netcdf4
    - nodejs
    - numpy
    - pandas >=2.1.0
    - pybtex
    - ruamel.yaml
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - livvkit
  commands:
    - livv --version

about:
  home: http://github.com/LIVVkit/LIVVkit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The land ice verification and validation toolkit

  description: |
    LIVVkit is a python-based toolkit for verification and validation of ice sheet models.
    It aims to provide both model V&V (numerical verification, physical validation) and 
    software V&V (code verification and performance validation).
  doc_url: https://livvkit.github.io/Docs
  dev_url: https://github.com/LIVVkit/LIVVkit

extra:
  recipe-maintainers:
    - mkstratos
    - jhkennedy
