{% set name = "livvkit" %}
{% set version = "3.1.0" %}
{% set sha256 = "98142516eb8dbf609fabb6584fff9f5c3ef18a29d3178cbdcfe2a8cdac04fc0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - livv = livvkit.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - netCDF4
    - matplotlib-base
    - jinja2
    - json_tricks ==3.11.0
    - pybtex
    - pandas

test:
  imports:
    - livvkit
  commands:
    - livv --version

about:
  home: http://github.com/LIVVkit/LIVVkit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The land ice verification and validation toolkit

  description: |
    LIVVkit is a python-based toolkit for verification and validation of ice sheet models.
    It aims to provide both model V&V (numerical verification, physical validation) and 
    software V&V (code verification and performance validation).
  doc_url: https://livvkit.github.io/Docs
  dev_url: https://github.com/LIVVkit/LIVVkit

extra:
  recipe-maintainers:
    - jhkennedy
