travis:
  secure:
    BINSTAR_TOKEN: r/jsLXtqMhZFwU2mn82il4ODJXd78O74Uv43hoNDwlp42ADdm+clK6HOFwatRLMww29npW8lPpdozVAiKXyUX0ePUQntf/3yoSjAH/c4iGTNVsn5kaIwMLLQO5Mo9KGVHBT5WtDF65vaSuCmzVS4bS7Y1yYx9LS6KXhhxKTeAnAVCPLtcjBqDYWq4vo6SquzHkE55vaDAkWG/AXpdIXwpTFtg/ZaXNHNCXoSg3BP75FjozlnIalVtxeLUGAj28FaLgMKp9Yfbi6nBO6WXLkpN8w2cA/tCUtjbN3PizuF92vxDyvnV6+7C4k72Etnaaq3PR253q5UEUbNtdXW8Qvb7auYzadpWagnzGjGyr0mREdCobTFhDdj2DqumlTQunEsaNQ7OoKk0ekELYvQucoJ6PXv11R2VMm5qjbkfnDZKBvMc/+Ka9RijMq/AtwIHztUNx7iAgtyb7ZIGzOKZOstUmtwxoiL+Hweq+r9pALAmKgVhzAcTfR6jjz41UZZGhT3MO8tjJchLfSI7GJB+wDgC9YjHYLTo1VuMK4o+FgPnLWhezGPWaJXCdgRoKFHL8D/rqvk80gP63opEwXMnV3KOI6Ud3K1+oVegZxHP3rN8qXWbbIuuckPnoBVcHKwLXqfglmOf48jO2IM5L2Ggzc6YE82R54rPVlLOc5Bi9ecdVw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
